rm -rf ./daemon/src/test
rm -rf ./p2p/src/test
rm -rf ./pricenode/src/test
rm -rf ./desktop/src/test
rm -rf ./common/src/test
rm -rf ./monitor/src/test
rm -rf ./seednode/src/test
rm -rf ./apitest/src/test
rm -rf ./cli/src/test
rm -rf ./assets/src/test
rm -rf ./core/src/test
