nano desktop/src/main/java/bisq/desktop/main/settings/about/AboutView.java
nano desktop/src/main/java/bisq/desktop/main/portfolio/bsqswaps/UnconfirmedBsqSwapsView.java
nano desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
nano desktop/src/main/java/bisq/desktop/main/overlays/windows/BtcEmptyWalletWindow.java
nano desktop/src/main/java/bisq/desktop/main/offer/bsq_swap/create_offer/BsqSwapCreateOfferView.java
nano desktop/src/main/java/bisq/desktop/main/offer/bsq_swap/take_offer/BsqSwapTakeOfferView.java
nano desktop/src/main/java/bisq/desktop/main/offer/bisq_v1/takeoffer/TakeOfferView.java
nano desktop/src/main/java/bisq/desktop/main/market/trades/TradesChartsView.java
nano monitor/src/main/java/bisq/monitor/metric/MarketStats.java
nano apitest/src/main/java/bisq/apitest/config/ApiTestConfig.java
nano cli/src/main/java/bisq/cli/CliMain.java
nano cli/src/main/java/bisq/cli/request/WalletsServiceRequest.java
nano cli/src/main/java/bisq/cli/opts/TakeOfferOptionParser.java
nano cli/src/main/java/bisq/cli/opts/CreateOfferOptionParser.java
nano cli/src/main/java/bisq/cli/table/builder/AbstractTableBuilder.java
nano cli/src/main/java/bisq/cli/table/builder/TradeTableColumnSupplier.java
nano cli/src/main/java/bisq/cli/table/builder/AddressBalanceTableBuilder.java
nano assets/src/main/java/bisq/asset/PrintTool.java
nano assets/src/main/java/bisq/asset/Asset.java
nano core/src/main/java/bisq/core/trade/statistics/TradeStatistics2.java
nano core/src/main/java/bisq/core/locale/CurrencyUtil.java
nano core/src/main/java/bisq/core/util/FormattingUtils.java
nano core/src/main/java/bisq/core/dao/node/explorer/JsonTxOutputType.java
nano core/src/main/java/bisq/core/offer/OfferUtil.java
nano core/src/main/java/bisq/core/offer/OfferPayloadBase.java
nano core/src/main/java/bisq/core/offer/Offer.java
nano core/src/main/java/bisq/core/offer/bsq_swap/BsqSwapOfferPayload.java
nano core/src/main/java/bisq/core/api/CoreOffersService.java
nano core/src/main/java/bisq/core/api/CoreWalletsService.java
